from __future__ import annotations

from ai_doc.analyzers.base import AnalysisContext, Analyzer, FindingAdapter
from ai_doc.domain.documents import Document, DocumentationSnapshot, DocumentProfile
from ai_doc.domain.evaluations import (
    EvaluationResult,
    Evaluator,
    PairwiseDimension,
    PairwiseDimensionResult,
    PairwiseOutcome,
    PairwiseSemanticEvaluator,
    PairwiseSemanticResult,
)
from ai_doc.domain.findings import Finding, FindingCategory, FindingSeverity
from ai_doc.domain.optimization import Candidate, ObjectiveVector
from ai_doc.domain.probes import (
    BehavioralObservation,
    ExecutionObservation,
    ExecutionObservationVerifier,
    ExecutionProbe,
    ExecutionProbeReport,
    ExecutionStatus,
    ObservationVerifier,
    PlanningProbeComparison,
    PlanningProbeReport,
    ProbeExpectationKind,
    ProbeExpectationOutcome,
    ProbeExpectationResult,
    ProbeMode,
    ProbeUsage,
    ScenarioProbeComparison,
    TargetProbe,
    VerifiedExecutionObservation,
    VerifiedObservation,
    WorkspaceDelta,
)
from ai_doc.extensions.process import (
    PROTOCOL_VERSION,
    ProcessAnalyzer,
    ProcessEvaluator,
    ProcessExtensionError,
    ProcessRecommendationPolicy,
    ProcessSemanticProvider,
    ProcessTokenCounter,
    ProcessTransport,
)
from ai_doc.optimizer.recommendation import RecommendationPolicy
from ai_doc.plugins.registry import ExtensionRegistry
from ai_doc.providers.base import LLMProvider
from ai_doc.providers.semantic import ProviderUsage, SemanticProvider, SemanticResponse
from ai_doc.tokens.counter import TokenCountAccuracy, TokenCounter

__all__ = [
    "AnalysisContext",
    "Analyzer",
    "BehavioralObservation",
    "Candidate",
    "Document",
    "DocumentProfile",
    "DocumentationSnapshot",
    "EvaluationResult",
    "Evaluator",
    "ExecutionObservation",
    "ExecutionObservationVerifier",
    "ExecutionProbe",
    "ExecutionProbeReport",
    "ExecutionStatus",
    "ExtensionRegistry",
    "Finding",
    "FindingAdapter",
    "FindingCategory",
    "FindingSeverity",
    "LLMProvider",
    "ObjectiveVector",
    "ObservationVerifier",
    "PairwiseDimension",
    "PairwiseDimensionResult",
    "PairwiseOutcome",
    "PairwiseSemanticEvaluator",
    "PairwiseSemanticResult",
    "PlanningProbeComparison",
    "PlanningProbeReport",
    "ProcessAnalyzer",
    "ProcessEvaluator",
    "ProcessExtensionError",
    "ProcessRecommendationPolicy",
    "ProcessSemanticProvider",
    "ProcessTokenCounter",
    "ProcessTransport",
    "PROTOCOL_VERSION",
    "ProviderUsage",
    "ProbeExpectationKind",
    "ProbeExpectationOutcome",
    "ProbeExpectationResult",
    "ProbeMode",
    "ProbeUsage",
    "RecommendationPolicy",
    "ScenarioProbeComparison",
    "SemanticProvider",
    "SemanticResponse",
    "TargetProbe",
    "TokenCounter",
    "TokenCountAccuracy",
    "VerifiedExecutionObservation",
    "VerifiedObservation",
    "WorkspaceDelta",
]
